### ISSUE TITLE
Error when running python example_script.py

### ISSUE THREAD

**Issue by amayank-umich** [stupplab/pythonic_martini#2]
I get the error 

Traceback (most recent call last):
  File "example_script.py", line 53, in <module>
    main.create_simulation_box(Lx,Ly,Lz, 
  File "/home/cbes/users/mayank/pythonic_martini/pythonic_martini/main.py", line 409, in create_simulation_box
    actual_nmol = _actual_molecules_added(boxfilename, '%s.itp'%molname, start_linenumber=0)
  File "/home/cbes/users/mayank/pythonic_martini/pythonic_martini/main.py", line 70, in _actual_molecules_added
    with open(filename, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'coPA_box.gro'

**Comment by amayank-umich** [comment]
This error is fixed now. There was an additional python library requirement `scipy`. 
`python example_script.py` should run now.
