### ISSUE TITLE
No such file or directory: 'coPA_box.gro'

### ISSUE THREAD

**Issue by hsai1020** [stupplab/pythonic_martini#3]
Redownloaded the newest version of pythonic_martini. The error we were getting before seems to still pop up.

Traceback (most recent call last):
  File "example_script.py", line 53, in <module>
    main.create_simulation_box(Lx,Ly,Lz, 
  File "/home/cbes/users/simon/pythonic_martini/pythonic_martini/main.py", line 409, in create_simulation_box
    actual_nmol = _actual_molecules_added(boxfilename, '%s.itp'%molname, start_linenumber=0)
  File "/home/cbes/users/simon/pythonic_martini/pythonic_martini/main.py", line 70, in _actual_molecules_added
    with open(filename, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'coPA_box.gro'

--Simon

**Comment by SimonEgner** [comment]
This issue gets resolved after one run of the example_script.py, but then a new error occurs.

Fatal error:
number of coordinates in coordinate file (coPA_water.gro, 16775)
             does not match topology (coPA.top, 16908)
